#ifndef VERSION_H
#define VERSION_H

#define ZEROPLAYER_VERSION_MAJOR 1
#define ZEROPLAYER_VERSION_MINOR 0
#define ZEROPLAYER_VERSION_PATCH 0

#define ZEROPLAYER_VERSION_STRING "1.0.0"

#define ZEROPLAYER_VERSION (ZEROPLAYER_VERSION_MAJOR * 10000 + \
                            ZEROPLAYER_VERSION_MINOR * 100 + \
                            ZEROPLAYER_VERSION_PATCH)

#endif /* VERSION_H */
